export { AuthPage } from './authPage';
export { SingInPage } from './singInPage';
export { MessagesPage } from './messagesPage';
export { ProfilePage } from './Profile';
export { ProfileEditPage } from './ProfileEdit';
export { PasswordEditPage } from './PasswordEdit';
export { AvatarEditPage } from './AvatarEdit';
export { NotFoundPage } from './notFoundPage';
export { ErrorPage } from './errorPage';
